r_sho_pitch :   # MX-28
   return_delay_time        : 1    # item name : value
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095

r_sho_pitch :   # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
l_sho_pitch :   # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
r_sho_roll :   # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
l_sho_roll :   # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
r_el :   # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
l_el :   # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
r_hip_yaw :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
l_hip_yaw :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
r_hip_roll :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
l_hip_roll :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
r_hip_pitch :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
l_hip_pitch :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
r_knee :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
l_knee :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
r_ank_pitch :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
l_ank_pitch :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
r_ank_roll :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
l_ank_roll :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
head_pan :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   
head_tilt :  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095
   